// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCiISCzXrw2rIWvLSmNw4_31mSkgqCeSs4',
    appId: '1:484038998673:web:a9eae0e267f5f2d7f65d30',
    messagingSenderId: '484038998673',
    projectId: 'cafe-e44a3',
    authDomain: 'cafe-e44a3.firebaseapp.com',
    storageBucket: 'cafe-e44a3.firebasestorage.app',
    measurementId: 'G-XJ2CX66GE7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCPuSrTtUPzRcEkbC3D38fqQw8fyp0KvXY',
    appId: '1:484038998673:android:0395ca458fe3c3dff65d30',
    messagingSenderId: '484038998673',
    projectId: 'cafe-e44a3',
    storageBucket: 'cafe-e44a3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBfJ1wZK79xxW9TmmKG2XR9LbWbDV8knXc',
    appId: '1:484038998673:ios:9a5f0b7ce27d8685f65d30',
    messagingSenderId: '484038998673',
    projectId: 'cafe-e44a3',
    storageBucket: 'cafe-e44a3.firebasestorage.app',
    iosBundleId: 'com.example.cafe',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBfJ1wZK79xxW9TmmKG2XR9LbWbDV8knXc',
    appId: '1:484038998673:ios:9a5f0b7ce27d8685f65d30',
    messagingSenderId: '484038998673',
    projectId: 'cafe-e44a3',
    storageBucket: 'cafe-e44a3.firebasestorage.app',
    iosBundleId: 'com.example.cafe',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCiISCzXrw2rIWvLSmNw4_31mSkgqCeSs4',
    appId: '1:484038998673:web:977ed7445e0bb6cdf65d30',
    messagingSenderId: '484038998673',
    projectId: 'cafe-e44a3',
    authDomain: 'cafe-e44a3.firebaseapp.com',
    storageBucket: 'cafe-e44a3.firebasestorage.app',
    measurementId: 'G-T0P89D50LX',
  );
}
